### ISSUE TITLE
Is there an equivalent to v4l2loopback's "video_nr" driver parameter?   

### ISSUE THREAD

**Issue by fangfufu** [webcamoid/akvcam#17]
In v4l2loopback, there is a driver parameter called ``video_nr``, which specifies the device-node minor number. Is it possible to specify this in akvcam? I basically want to stop akvcam to occupy /dev/video0 and /dev/video1.

**Comment by hipersayanX** [comment]
No, I prefer to let the kernel decide which number corresponds to each device, this way it avoids collisions with other drivers.

**Comment by fangfufu** [comment]
But that way it messes up the order of my webcams. :(

**Comment by hipersayanX** [comment]
Not sure if I want to do that way, I think it will cause more problems than solutions, let me think it.

**Comment by fangfufu** [comment]
Personally, I think it is would be a nice to give users the option to specify things. You can leave the default behaviour as it is. 

The only reason I opened this ticket is because I hardcoded the webcam path in some of my scripts... lol.

**Comment by vStone** [comment]
You could resolve this by creating a fixed symlink using udev matching the `camera\#\description` with `ENV{ID_V4L_PRODUCT}`

**Comment by hipersayanX** [comment]
At the end I'll have to implement this, this could be useful in the future.

**Comment by fangfufu** [comment]
> At the end I'll have to implement this, this could be useful in the future.

How comes?

**Comment by hipersayanX** [comment]
@fangfufu 

>How comes?

I need the devices to be predictable so I can simplify my [waitForDevices function](https://github.com/webcamoid/webcamoid/blob/90a7d3e01b3bd513aeb12d70aea101c395e5b36a/libAvKys/Plugins/VirtualCamera/src/v4l2sys/VCamIPC/src/ipcbridge.cpp#L2328), instead of waiting for all v4l2 devices created by all drivers and then waiting for the same number of devices to appear, I can wait for the specific devices to appear. I did not figured out at beginning :sweat_smile:

**Comment by hipersayanX** [comment]
I've implemented this in the latest commit.

**Comment by fangfufu** [comment]
Cool! I will close the issue for now. :)

**Comment by StefanBruens** [comment]
instead of polling for the devices, you should listen to the relevant udev "ADD" events.
